# Project
version=1.0.0
group=com.mozi1924.yefira
java_version=17

# Common Mod Properties
minecraft_version=1.20.1
mod_name=Yefira
mod_author=mozi1924
mod_id=yefira
license=GPL-3.0
credits=
description=Real-time bidirectional synchronization bridge between Minecraft and Blender (MoziToolKit) via WebSocket.
minecraft_version_range=[1.20, 1.21)
fabric_minecraft_version_range=~1.20
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9
loom_version=1.8-SNAPSHOT

# Forge
forge_version=47.3.0
forge_loader_version_range=[47,)

# JVM & Build
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

