# Project
version=1.0.0
group=com.mozi1924.yefira
java_version=25

# Common Mod Properties
minecraft_version=26.2
mod_name=Yefira
mod_author=mozi1924
mod_id=yefira
license=GPL-3.0
credits=
description=Real-time bidirectional synchronization bridge between Minecraft and Blender (MoziToolKit) via WebSocket.
minecraft_version_range=[26.2, 26.3)
neo_form_version=26.2-2

# Fabric
fabric_version=0.157.0+26.2
fabric_loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# NeoForge
neoforge_version=26.2.0.75
neoforge_loader_version_range=[1,)

# JVM & Build
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

