plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        client {
            client()
            gameDirectory = rootProject.file('run/forge')
        }
        server {
            server()
            gameDirectory = rootProject.file('run/forge_server')
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

configurations {
    shade
    implementation.extendsFrom shade
}

mixin {
    add sourceSets.main, "yefira-refmap.json"
    config "yefira.mixins.json"
    config "yefira.client.mixins.json"
}

dependencies {
    compileOnly('net.fabricmc:sponge-mixin:0.17.3+mixin.0.8.7')
    annotationProcessor('org.spongepowered:mixin:0.8.5:processor')
    annotationProcessor('io.github.llamalad7:mixinextras-common:0.5.3')

    shade "org.java-websocket:Java-WebSocket:1.5.6"
    additionalRuntimeClasspath "org.java-websocket:Java-WebSocket:1.5.6"
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes([
            'MixinConfigs': 'yefira.mixins.json,yefira.client.mixins.json'
        ])
    }
    from {
        configurations.shade.collect { it.isDirectory() ? it : zipTree(it) }
    } {
        exclude 'META-INF/*.SF'
        exclude 'META-INF/*.DSA'
        exclude 'META-INF/*.RSA'
        exclude 'META-INF/MANIFEST.MF'
        exclude 'META-INF/INDEX.LIST'
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named(variant) {
        attributes {
            attribute(loaderAttribute, 'forge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, 'forge')
            }
        }
    }
}
