plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
            gameDirectory = rootProject.file('run/neoforge')
        }
        server {
            server()
            gameDirectory = rootProject.file('run/neoforge_server')
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation "org.java-websocket:Java-WebSocket:1.5.6"
    jarJar "org.java-websocket:Java-WebSocket:1.5.6"
    additionalRuntimeClasspath "org.java-websocket:Java-WebSocket:1.5.6"
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named(variant) {
        attributes {
            attribute(loaderAttribute, 'neoforge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName, it.getTaskName(null, 'jarJar')].each { variant ->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, 'neoforge')
            }
        }
    }
}
